spring:
  application:
    name: Emails
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: producto-notification-consumers
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
app:
  topic:
    name: producto-notification
  servicio:
    topic:
      name: servicio-notification
