spring:
  application:
    name: OrdenCompra
server:
  port: 6000

resilience4j:
  circuitbreaker:
    instances:
      ordenService:
        register-health-indicator: true
        sliding-window-type: count-based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      detalleOrdenService:
        register-health-indicator: true
        sliding-window-type: count-based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

  retry:
    instances:
      ordenService:
        max-attempts: 3
        wait-duration: 2s
      detalleOrdenService:
        max-attempts: 3
        wait-duration: 2s
