spring:
  application:
    name: Usuario
resilience4j:
  circuitbreaker:
    instances:
      usuarioService:
        register-health-indicator: true
        sliding-window-type: count-based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      usuarioService:
        max-attempts: 3
        wait-duration: 2s